version: 20
jobs:
- name: cc
  jobExecutor: maven-jdk11-builder
  steps:
  - !CheckoutStep
    name: cc
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: deploy
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - mvn clean compile package deploy -U
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: github-sync
  jobExecutor: local-server-executor
  steps:
  - !PushRepository
    name: github-sync
    remoteUrl: https://github.com/vanillazi/native-image-helper.git
    userName: vanillazi
    passwordSecret: vanillazi-github-sync
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
